<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Product extends \App\Entity\Product implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'prodcutName', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'boxSize', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'boxColor', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'roseNumber', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'roseColor', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'ligneCommande', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'categorie', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'image', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'imageRoseNumber', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'prix', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'imageCategorie', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'macronNumber', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'hautImage', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'descriptionBox', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'stock'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'prodcutName', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'boxSize', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'boxColor', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'roseNumber', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'roseColor', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'ligneCommande', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'categorie', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'image', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'imageRoseNumber', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'prix', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'imageCategorie', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'macronNumber', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'hautImage', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'descriptionBox', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'stock'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Product $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getProdcutName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProdcutName', []);

        return parent::getProdcutName();
    }

    /**
     * {@inheritDoc}
     */
    public function setProdcutName(string $prodcutName): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProdcutName', [$prodcutName]);

        return parent::setProdcutName($prodcutName);
    }

    /**
     * {@inheritDoc}
     */
    public function getBoxSize(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBoxSize', []);

        return parent::getBoxSize();
    }

    /**
     * {@inheritDoc}
     */
    public function setBoxSize(string $boxSize): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBoxSize', [$boxSize]);

        return parent::setBoxSize($boxSize);
    }

    /**
     * {@inheritDoc}
     */
    public function getBoxColor(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBoxColor', []);

        return parent::getBoxColor();
    }

    /**
     * {@inheritDoc}
     */
    public function setBoxColor(string $boxColor): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBoxColor', [$boxColor]);

        return parent::setBoxColor($boxColor);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoseNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoseNumber', []);

        return parent::getRoseNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoseNumber($roseNumber): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoseNumber', [$roseNumber]);

        parent::setRoseNumber($roseNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoseColor(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoseColor', []);

        return parent::getRoseColor();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoseColor(string $roseColor): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoseColor', [$roseColor]);

        return parent::setRoseColor($roseColor);
    }

    /**
     * {@inheritDoc}
     */
    public function getLigneCommande()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLigneCommande', []);

        return parent::getLigneCommande();
    }

    /**
     * {@inheritDoc}
     */
    public function setLigneCommande($ligneCommande): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLigneCommande', [$ligneCommande]);

        parent::setLigneCommande($ligneCommande);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategorie(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategorie', []);

        return parent::getCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategorie(string $categorie): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategorie', [$categorie]);

        return parent::setCategorie($categorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage(string $image): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageRoseNumber(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageRoseNumber', []);

        return parent::getImageRoseNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageRoseNumber(string $imageRoseNumber): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageRoseNumber', [$imageRoseNumber]);

        return parent::setImageRoseNumber($imageRoseNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix', []);

        return parent::getPrix();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix(float $prix): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix', [$prix]);

        return parent::setPrix($prix);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageCategorie(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageCategorie', []);

        return parent::getImageCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageCategorie(string $imageCategorie): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageCategorie', [$imageCategorie]);

        return parent::setImageCategorie($imageCategorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getMacronNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMacronNumber', []);

        return parent::getMacronNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setMacronNumber($macronNumber): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMacronNumber', [$macronNumber]);

        parent::setMacronNumber($macronNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getHautImage(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHautImage', []);

        return parent::getHautImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setHautImage(?string $hautImage): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHautImage', [$hautImage]);

        return parent::setHautImage($hautImage);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptionBox(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptionBox', []);

        return parent::getDescriptionBox();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptionBox(?string $descriptionBox): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptionBox', [$descriptionBox]);

        return parent::setDescriptionBox($descriptionBox);
    }

    /**
     * {@inheritDoc}
     */
    public function getStock(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStock', []);

        return parent::getStock();
    }

    /**
     * {@inheritDoc}
     */
    public function setStock(?int $stock): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStock', [$stock]);

        return parent::setStock($stock);
    }

    /**
     * {@inheritDoc}
     */
    public function setImagesAccordingToSwitch($product)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImagesAccordingToSwitch', [$product]);

        return parent::setImagesAccordingToSwitch($product);
    }

    /**
     * {@inheritDoc}
     */
    public function uploadImageProduct($uploadedFile, $destination)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'uploadImageProduct', [$uploadedFile, $destination]);

        return parent::uploadImageProduct($uploadedFile, $destination);
    }

}
