<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class LigneCommande extends \App\Entity\LigneCommande implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\LigneCommande' . "\0" . 'id', '' . "\0" . 'App\\Entity\\LigneCommande' . "\0" . 'idProduit', '' . "\0" . 'App\\Entity\\LigneCommande' . "\0" . 'quantite', '' . "\0" . 'App\\Entity\\LigneCommande' . "\0" . 'idOrder', '' . "\0" . 'App\\Entity\\LigneCommande' . "\0" . 'litteRose', '' . "\0" . 'App\\Entity\\LigneCommande' . "\0" . 'type', '' . "\0" . 'App\\Entity\\LigneCommande' . "\0" . 'card', '' . "\0" . 'App\\Entity\\LigneCommande' . "\0" . 'messageCard', '' . "\0" . 'App\\Entity\\LigneCommande' . "\0" . 'couvercle', '' . "\0" . 'App\\Entity\\LigneCommande' . "\0" . 'messageCouvercle', '' . "\0" . 'App\\Entity\\LigneCommande' . "\0" . 'suprise', '' . "\0" . 'App\\Entity\\LigneCommande' . "\0" . 'nameR', '' . "\0" . 'App\\Entity\\LigneCommande' . "\0" . 'lastNameR', '' . "\0" . 'App\\Entity\\LigneCommande' . "\0" . 'adressR', '' . "\0" . 'App\\Entity\\LigneCommande' . "\0" . 'phoneNumverR', '' . "\0" . 'App\\Entity\\LigneCommande' . "\0" . 'shipdate', '' . "\0" . 'App\\Entity\\LigneCommande' . "\0" . 'typeLivraison', '' . "\0" . 'App\\Entity\\LigneCommande' . "\0" . 'commentaire', '' . "\0" . 'App\\Entity\\LigneCommande' . "\0" . 'status', '' . "\0" . 'App\\Entity\\LigneCommande' . "\0" . 'macaronPersonnalise'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\LigneCommande' . "\0" . 'id', '' . "\0" . 'App\\Entity\\LigneCommande' . "\0" . 'idProduit', '' . "\0" . 'App\\Entity\\LigneCommande' . "\0" . 'quantite', '' . "\0" . 'App\\Entity\\LigneCommande' . "\0" . 'idOrder', '' . "\0" . 'App\\Entity\\LigneCommande' . "\0" . 'litteRose', '' . "\0" . 'App\\Entity\\LigneCommande' . "\0" . 'type', '' . "\0" . 'App\\Entity\\LigneCommande' . "\0" . 'card', '' . "\0" . 'App\\Entity\\LigneCommande' . "\0" . 'messageCard', '' . "\0" . 'App\\Entity\\LigneCommande' . "\0" . 'couvercle', '' . "\0" . 'App\\Entity\\LigneCommande' . "\0" . 'messageCouvercle', '' . "\0" . 'App\\Entity\\LigneCommande' . "\0" . 'suprise', '' . "\0" . 'App\\Entity\\LigneCommande' . "\0" . 'nameR', '' . "\0" . 'App\\Entity\\LigneCommande' . "\0" . 'lastNameR', '' . "\0" . 'App\\Entity\\LigneCommande' . "\0" . 'adressR', '' . "\0" . 'App\\Entity\\LigneCommande' . "\0" . 'phoneNumverR', '' . "\0" . 'App\\Entity\\LigneCommande' . "\0" . 'shipdate', '' . "\0" . 'App\\Entity\\LigneCommande' . "\0" . 'typeLivraison', '' . "\0" . 'App\\Entity\\LigneCommande' . "\0" . 'commentaire', '' . "\0" . 'App\\Entity\\LigneCommande' . "\0" . 'status', '' . "\0" . 'App\\Entity\\LigneCommande' . "\0" . 'macaronPersonnalise'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (LigneCommande $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdProduit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdProduit', []);

        return parent::getIdProduit();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdOrder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdOrder', []);

        return parent::getIdOrder();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdProduit($idProduit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdProduit', [$idProduit]);

        return parent::setIdProduit($idProduit);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIdProduit(\App\Entity\Product $idProduit): \App\Entity\LigneCommande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIdProduit', [$idProduit]);

        return parent::removeIdProduit($idProduit);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuantite(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuantite', []);

        return parent::getQuantite();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuantite(int $quantite): \App\Entity\LigneCommande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuantite', [$quantite]);

        return parent::setQuantite($quantite);
    }

    /**
     * {@inheritDoc}
     */
    public function setIdOrder($idOrder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdOrder', [$idOrder]);

        return parent::setIdOrder($idOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIdOrder(\App\Entity\Commande $idOrder): \App\Entity\LigneCommande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIdOrder', [$idOrder]);

        return parent::removeIdOrder($idOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getLitteRose()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLitteRose', []);

        return parent::getLitteRose();
    }

    /**
     * {@inheritDoc}
     */
    public function setLitteRose($litteRose): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLitteRose', [$litteRose]);

        parent::setLitteRose($litteRose);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getCard()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCard', []);

        return parent::getCard();
    }

    /**
     * {@inheritDoc}
     */
    public function setCard($card): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCard', [$card]);

        parent::setCard($card);
    }

    /**
     * {@inheritDoc}
     */
    public function getMessageCard()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMessageCard', []);

        return parent::getMessageCard();
    }

    /**
     * {@inheritDoc}
     */
    public function setMessageCard($messageCard): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMessageCard', [$messageCard]);

        parent::setMessageCard($messageCard);
    }

    /**
     * {@inheritDoc}
     */
    public function getCouvercle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCouvercle', []);

        return parent::getCouvercle();
    }

    /**
     * {@inheritDoc}
     */
    public function setCouvercle($couvercle): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCouvercle', [$couvercle]);

        parent::setCouvercle($couvercle);
    }

    /**
     * {@inheritDoc}
     */
    public function getMessageCouvercle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMessageCouvercle', []);

        return parent::getMessageCouvercle();
    }

    /**
     * {@inheritDoc}
     */
    public function setMessageCouvercle($messageCouvercle): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMessageCouvercle', [$messageCouvercle]);

        parent::setMessageCouvercle($messageCouvercle);
    }

    /**
     * {@inheritDoc}
     */
    public function getSuprise()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSuprise', []);

        return parent::getSuprise();
    }

    /**
     * {@inheritDoc}
     */
    public function setSuprise($suprise): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSuprise', [$suprise]);

        parent::setSuprise($suprise);
    }

    /**
     * {@inheritDoc}
     */
    public function getNameR()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameR', []);

        return parent::getNameR();
    }

    /**
     * {@inheritDoc}
     */
    public function setNameR($nameR): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNameR', [$nameR]);

        parent::setNameR($nameR);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastNameR()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastNameR', []);

        return parent::getLastNameR();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastNameR($lastNameR): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastNameR', [$lastNameR]);

        parent::setLastNameR($lastNameR);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdressR()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdressR', []);

        return parent::getAdressR();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdressR($adressR): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdressR', [$adressR]);

        parent::setAdressR($adressR);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoneNumverR()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoneNumverR', []);

        return parent::getPhoneNumverR();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoneNumverR($phoneNumverR): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoneNumverR', [$phoneNumverR]);

        parent::setPhoneNumverR($phoneNumverR);
    }

    /**
     * {@inheritDoc}
     */
    public function getShipdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShipdate', []);

        return parent::getShipdate();
    }

    /**
     * {@inheritDoc}
     */
    public function setShipdate($shipdate): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShipdate', [$shipdate]);

        parent::setShipdate($shipdate);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeLivraison(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeLivraison', []);

        return parent::getTypeLivraison();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeLivraison(string $typeLivraison): \App\Entity\LigneCommande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeLivraison', [$typeLivraison]);

        return parent::setTypeLivraison($typeLivraison);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommentaire(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommentaire', []);

        return parent::getCommentaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommentaire(?string $commentaire): \App\Entity\LigneCommande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommentaire', [$commentaire]);

        return parent::setCommentaire($commentaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getMacaronPersonnalise()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMacaronPersonnalise', []);

        return parent::getMacaronPersonnalise();
    }

    /**
     * {@inheritDoc}
     */
    public function setMacaronPersonnalise(?string $macaronPersonnalise): \App\Entity\LigneCommande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMacaronPersonnalise', [$macaronPersonnalise]);

        return parent::setMacaronPersonnalise($macaronPersonnalise);
    }

}
