<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKAo9nex\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKAo9nex/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKAo9nex.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKAo9nex\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKAo9nex\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'KAo9nex',
    'container.build_id' => 'aa4c5065',
    'container.build_time' => 1632480767,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKAo9nex');
