<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAExE5Kd\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAExE5Kd/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAExE5Kd.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAExE5Kd\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerAExE5Kd\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'AExE5Kd',
    'container.build_id' => '20e97515',
    'container.build_time' => 1632485584,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAExE5Kd');
